### PR TITLE
Add useTube() to change tubes after connection

### PR DESCRIPTION
**Pull request by markkimsal**
Currently, I am unable to push messages to multiple different tubes because the only "use" command is inside the constructor.

### CODE REVIEW

**Comment by kelunik** [comment]
@markkimsal This is currently by design. The issue with changing tubes appears if you share one connection within multiple different objects / services. Suddenly things are passed to the wrong tube if one changes the tube.

How about using different connections for different tubes? You could also wrap the client and have an API that accepts an additional parameter specifying the tube for each command, that then automatically manages multiple connections.

Thoughts?

**Comment by markkimsal** [comment]
I'm reading a stream of json objects and want to fan out each message to a tube of the object's "type" property.  Not-being able to change tubes is a deal breaker for a producer of beanstalk jobs.

Perhaps dynamically creating connections for each json object "type" bight be a workable solution in a synchronous environment.  But dynamically creating async connections and trying to manage or re-use them?  Too complicated.

I'm not sure what's being protected here, if you are unsure what tube is being used before a **put**, simply **use** the correct tube before a **put**.  If multiple parts of a program are all sharing one connection asynchronously, a situation where **reserves** are going to the wrong tubes because of competing **watches** and **ignores** is just as likely as **puts** going to the wrong tubes because of competing **uses**

A more innovative approach might be to design a library that combines **use** and **put** into one userland function.  All other beanstalk client libraries have a **use** function.  But why do none of them have a "putInto($tube, $job, $pri, $delay)" function which combines both functions into one transaction-like whole?  This would be akin to a library supporting "upsert" functionality on a database which doesn't natively support upserts.

**Comment by bwoebi** [comment]
Having it as transaction (i.e. use, put, (re-)use original tube) should work fine too, but may be a lot of overhead of changing tubes all the times back and forth.

@kelunik I disagree here to some extent. It is good to forbid mutating connection state if you share. But if you own the connection, you should be able to change connection state too.
You are blocking a whole class of use cases for preventing illegitimate use in other cases. Perhaps have a separate BeanstalkTubeClient extends BeanstalkClient providing that method for changing tubes. But it should definitely exist.

**Comment by kelunik** [comment]
@markkimsal `putInto` is a good idea, I like that. Regarding `watch` and `ignore`, I think I will implement something like I did in `amphp/redis` for subscriptions, making it easily shareable.

**Comment by markkimsal** [comment]
If you're a producer of messages, and you're only putting into 1 tube, the existing functionality is fine.

If you're a consumer, and you're at most publishing to 1 reply tube, the existing functionality is fine.

If you're a producer writing to multiple tubes, putInto() adds 1 extra command consistently to every put. 

In my case, I'm executing a use() before each put() anyhow.  The overhead of tracking the last used tube is not worth the optimization of saving one command.

Are there valid use cases where you're switching tubes, writing a dozen messages to one tube, and then switching tubes and writing another handful of messages?  If so, is that worth optimizing, or is that tipping into the mythical "power user" use case?

If putInto() switches back, then it would add 1 extra command to my use case.  If I'm going to use putInto(), I'm going to use it all over the place and not keep track of any "default" tube.

If putInto() does not revert to the last used tube, then put() becomes slightly obfuscated as to which tube the job will end up in.

option 1 put() can call putInto() and pass the default configured from the conn string ?tube=xxx.  This gives the feeling that putInto() is "switching back" to the default tube, but only adds overhead when needed.

option 2  use() and put() can behave like the protocol describes, and putInto() leaves the tube changed but it's not readily apparent.

option 3  get rid of put() for putInto()

**Comment by kelunik** [comment]
I would probably have gone with 3, but 1 seems to be another good option. I'm not that used to Beanstalk, have hardly used it so far. Is `put` the only command affected by `use` or are there others like `bury` that need to use the right tube? I think I'll reread the spec in the coming days.

**Comment by kelunik** [comment]
Merged for now, but needs a fix before release, otherwise we end up with the default tube after automatic reconnect.

**Comment by kelunik** [comment]
@markkimsal The new `master` (based on Amp v2) fixes it also for auto-reconnect: https://github.com/amphp/beanstalk/commit/8ba0fbfa5465a9a261593f06804d00b5dda3f29f#diff-cee99ac9518f534076eb4db35f782138R81

Do you need a release for Amp v1 or is a release for Amp v2 enough? Totally forgot to tag something here.

**Pull request merged**
